version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: bozankaya_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  postgres-db:
    image: postgres:15-alpine
    container_name: bozankaya_db
    environment:
      POSTGRES_USER: hacer
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: telemetry_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: